### PR TITLE
[JENKINS-38712] Avoid deep indentation

### PR DESCRIPTION
**Pull request by jglick**
See [JENKINS-38712](https://issues.jenkins-ci.org/browse/JENKINS-38712) for why I did not do this to begin with: there are drawbacks to the new control.

jenkins-38712

@reviewbybees

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
🐝

**Comment by recampbell** [comment]
There's not much of a visual separation between "Legacy SCM" and its apparent sub-options. They appear to be alternatives.

Perhaps if we added some help text (ie, the (?) icon) to this option and its sub option, it would help visual clarify the relationship of these radio boxes and also guide the user?

**Comment by recampbell** [comment]
OK, I can't figure out how to edit a review. Was trying to leave a 🐛 to say that we should discuss this.

**Comment by jglick** [comment]
Revised appearance with only *Legacy SCM*:

revised

Including also *Modern SCM*:

revised-with-modern

As I noted before, the original controls work better when you have sufficient horizontal space to display it, but we have no way that I know of to reduce the indentation.

**Comment by jglick** [comment]
BTW it is also possible to use `f:block` to show a blurb unconditionally (in addition to or instead of the help button), as is done beneath section titles for *Pipeline Libraries* and *Global Pipeline Libraries*.

**Comment by jglick** [comment]
I checked the appearance in 2.19.1 but it is no different, pending https://github.com/jenkinsci/cloudbees-folder-plugin/pull/67 and some equivalent for global configuration.

**Comment by recampbell** [comment]
OK, I think this is a signficant improvement over what we have and directly addresses the raised issue. There's still some confusion since Legacy SCM looks like an alternative to Subversion, but this is a big step forward IMO and we should ship like this.

🐝

**Comment by oleg-nenashev** [comment]
🐝

**Pull request merged**
