### PR TITLE
JENKINS-46721: Expect library sources in custom subdirectory

### PR DESCRIPTION
**Pull request by petr-motejlek**
[JENKINS-46721](https://issues.jenkins-ci.org/browse/JENKINS-46721)

### CODE REVIEW

**Comment by petr-motejlek** [comment]
Oh. There's a failed build. But after examining it, it couldn't have failed because of changes in this PR. It failed because it could not download a build of the credentials plugin.

**Comment by basil** [comment]
Nice! My company has the same problem, and I'd really like for this functionality to be available.

**Comment by basil** [comment]
Any update on this pull request? It would be nice to have this feature available.

**Comment by jglick** [comment]
Also best to address [JENKINS-44481](https://issues.jenkins-ci.org/browse/JENKINS-44481) in the same change.

**Comment by adamvoss** [comment]
@jglick I'm really just looking for the ability to load a library from a directory within the current workspace ([similar StackOverflow question](https://stackoverflow.com/q/46213913/1072626)).  Since my workspace comes from a SCM repository, this PR would address that need in a roundabout way so I have been looking into this.

However, with that being my use case (which SO shows to be shared by others) is this really the right solution?  It seems like it would be better to have a way to specify I actually want to load from the file system rather than saying to do a new SCM (Git) clone and then look at a sub-directory.

> Also best to address [JENKINS-44481](https://issues.jenkins-ci.org/browse/JENKINS-44481) in the same change.

I commented on that issue.  I'm not entirely sure if it applies or is desirable here.

**Comment by dwnusbaum** [comment]
Closing in favor of https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/99.

**Pull request closed without merging**
